/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Saved authentication tokens for reuse across sessions */
export interface SavedTokens {
  accessToken: string
  refreshToken: string
  userId: string
  isPremiumUser: boolean
}
/** A single item in a shopping list */
export interface ListItem {
  id: string
  listId: string
  name: string
  details: string
  isChecked: boolean
  quantity?: string
  category?: string
  userId?: string
  productUpc?: string
}
/** A shopping list containing items */
export interface List {
  id: string
  name: string
  items: Array<ListItem>
}
/** AnyList API client for interacting with the AnyList service */
export declare class AnyListClient {
  /** Login with email and password */
  static login(email: string, password: string): Promise<AnyListClient>
  /** Create client from saved tokens */
  static fromTokens(tokens: SavedTokens): AnyListClient
  /** Export tokens for later reuse */
  exportTokens(): SavedTokens
  /** Get the user ID */
  userId(): string
  /** Check if user has premium subscription */
  isPremiumUser(): boolean
  /** Get the client identifier */
  clientIdentifier(): string
  /** Get all shopping lists */
  getLists(): Promise<Array<List>>
  /** Create a new shopping list */
  createList(name: string): Promise<List>
  /** Add an item to a list */
  addItem(listId: string, name: string): Promise<ListItem>
  /** Add an item to a list with additional details */
  addItemWithDetails(listId: string, name: string, quantity?: string | undefined | null, details?: string | undefined | null, category?: string | undefined | null): Promise<ListItem>
}
