/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main AnyList client for interacting with the API */
export declare class AnyListClient {
  /** Login to AnyList with email and password */
  static login(email: string, password: string): Promise<AnyListClient>;
  /** Create a client from saved tokens (for resuming sessions) */
  static fromTokens(tokens: SavedTokens): AnyListClient;
  /** Get the saved tokens for this session */
  getTokens(): SavedTokens;
  /** Get all lists */
  getLists(): Promise<Array<List>>;
  /** Create a new list */
  createList(name: string): Promise<List>;
  /** Get a specific list by ID */
  getListById(listId: string): Promise<List>;
  /** Get a list by name */
  getListByName(name: string): Promise<List>;
  /** Rename a list */
  renameList(listId: string, newName: string): Promise<void>;
  /** Add an item to a list */
  addItem(listId: string, name: string): Promise<ListItem>;
  /** Add an item with details to a list */
  addItemWithDetails(
    listId: string,
    name: string,
    quantity?: string | undefined | null,
    note?: string | undefined | null,
    category?: string | undefined | null,
  ): Promise<ListItem>;
  /** Delete an item from a list */
  deleteItem(listId: string, itemId: string): Promise<void>;
  /** Cross off (check) an item */
  crossOffItem(listId: string, itemId: string): Promise<void>;
  /** Uncheck an item */
  uncheckItem(listId: string, itemId: string): Promise<void>;
  /** Update an existing item */
  updateItem(
    listId: string,
    itemId: string,
    name: string,
    quantity?: string | undefined | null,
    note?: string | undefined | null,
    category?: string | undefined | null,
  ): Promise<void>;
  /** Delete multiple items at once */
  bulkDeleteItems(listId: string, itemIds: Array<string>): Promise<void>;
  /** Delete all crossed off (checked) items from a list */
  deleteAllCrossedOffItems(listId: string): Promise<void>;
  /** Get all recipes */
  getRecipes(): Promise<Array<Recipe>>;
  /** Get a specific recipe by ID */
  getRecipeById(recipeId: string): Promise<Recipe>;
  /** Get a recipe by name */
  getRecipeByName(name: string): Promise<Recipe>;
  /** Create a new recipe with full metadata support */
  createRecipe(options: CreateRecipeOptions): Promise<Recipe>;
  /** Add recipe ingredients to a list with optional scale factor */
  addRecipeToList(
    recipeId: string,
    listId: string,
    scaleFactor?: number | undefined | null,
  ): Promise<void>;
  /**
   * Update an existing recipe
   * Note: The recipe name cannot be changed (use the existing name in options)
   */
  updateRecipe(recipeId: string, options: CreateRecipeOptions): Promise<Recipe>;
  /** Delete a recipe */
  deleteRecipe(recipeId: string): Promise<void>;
  /** Delete a list */
  deleteList(listId: string): Promise<void>;
  /**
   * Upload a photo for use with recipes
   * Returns the photo ID which can be used with createRecipe
   */
  uploadPhoto(data: Buffer, filename: string): Promise<string>;
  /** Create a new category in a list */
  createCategory(
    listId: string,
    categoryGroupId: string,
    name: string,
  ): Promise<Category>;
  /** Delete a category from a list */
  deleteCategory(listId: string, categoryId: string): Promise<void>;
  /** Rename a category */
  renameCategory(
    listId: string,
    categoryGroupId: string,
    categoryId: string,
    newName: string,
  ): Promise<void>;
  /** Get all stores for a list */
  getStoresForList(listId: string): Promise<Array<Store>>;
  /** Create a new store for a list */
  createStore(listId: string, name: string): Promise<Store>;
  /** Update a store's name */
  updateStore(listId: string, storeId: string, newName: string): Promise<void>;
  /** Get store filters for a list */
  getStoreFiltersForList(listId: string): Promise<Array<StoreFilter>>;
  /** Delete a store from a list */
  deleteStore(listId: string, storeId: string): Promise<void>;
  /** Get all favourite items across all lists */
  getFavourites(): Promise<Array<FavouriteItem>>;
  /** Get all favourites lists (starter lists) */
  getFavouritesLists(): Promise<Array<FavouritesList>>;
  /** Get favourites for a specific shopping list */
  getFavouritesForList(shoppingListId: string): Promise<FavouritesList>;
  /** Add a favourite item to the default list */
  addFavourite(
    name: string,
    category?: string | undefined | null,
  ): Promise<FavouriteItem>;
  /** Add a favourite item to a specific list */
  addFavouriteToList(
    listId: string,
    name: string,
    category?: string | undefined | null,
  ): Promise<FavouriteItem>;
  /** Remove a favourite item from a list */
  removeFavourite(listId: string, itemId: string): Promise<void>;
  /** Add a favourite item to a shopping list */
  addFavouriteToShoppingList(
    favouriteListId: string,
    favouriteId: string,
    shoppingListId: string,
  ): Promise<ListItem>;
  /** Get meal plan events for a date range */
  getMealPlanEvents(
    startDate: string,
    endDate: string,
  ): Promise<Array<MealPlanEvent>>;
  /** Create a meal plan event */
  createMealPlanEvent(
    calendarId: string,
    date: string,
    recipeId?: string | undefined | null,
    title?: string | undefined | null,
    labelId?: string | undefined | null,
  ): Promise<MealPlanEvent>;
  /** Update a meal plan event */
  updateMealPlanEvent(
    calendarId: string,
    eventId: string,
    date: string,
    recipeId?: string | undefined | null,
    title?: string | undefined | null,
    labelId?: string | undefined | null,
  ): Promise<void>;
  /** Delete a meal plan event */
  deleteMealPlanEvent(calendarId: string, eventId: string): Promise<void>;
  /** Add meal plan ingredients to a shopping list */
  addMealPlanIngredientsToList(
    listId: string,
    startDate: string,
    endDate: string,
  ): Promise<void>;
  /** Enable iCalendar sync and get the URL */
  enableIcalendar(): Promise<ICalendarInfo>;
  /** Disable iCalendar sync */
  disableIcalendar(): Promise<void>;
  /** Get the iCalendar URL if enabled */
  getIcalendarUrl(): Promise<string | null>;
  /** Get all recipe collections */
  getRecipeCollections(): Promise<Array<RecipeCollection>>;
  /** Create a new recipe collection */
  createRecipeCollection(name: string): Promise<RecipeCollection>;
  /** Delete a recipe collection */
  deleteRecipeCollection(collectionId: string): Promise<void>;
  /** Add a recipe to a collection */
  addRecipeToCollection(collectionId: string, recipeId: string): Promise<void>;
  /** Remove a recipe from a collection */
  removeRecipeFromCollection(
    collectionId: string,
    recipeId: string,
  ): Promise<void>;
}

/** A category for organizing list items */
export interface Category {
  id: string;
  name: string;
  icon?: string;
  sortIndex: number;
}

/** A group of categories */
export interface CategoryGroup {
  id: string;
  name: string;
  categories: Array<Category>;
}

/** Options for creating a new recipe */
export interface CreateRecipeOptions {
  /** Recipe name (required) */
  name: string;
  /** List of ingredients */
  ingredients: Array<IngredientInput>;
  /** Preparation/cooking steps */
  preparationSteps: Array<string>;
  /** Recipe notes/description */
  note?: string;
  /** Source name (e.g., "Web", "Cookbook") */
  sourceName?: string;
  /** Source URL */
  sourceUrl?: string;
  /** Serving size (e.g., "4 servings") */
  servings?: string;
  /** Prep time in minutes */
  prepTime?: number;
  /** Cook time in minutes */
  cookTime?: number;
  /** Rating from 1-5 */
  rating?: number;
  /** Nutritional information */
  nutritionalInfo?: string;
  /** Photo ID (from upload_photo) */
  photoId?: string;
}

/** A favourite item (starter list item) */
export interface FavouriteItem {
  id: string;
  listId: string;
  name: string;
  quantity?: string;
  details?: string;
  category?: string;
}

/** A list of favourite items (starter list) */
export interface FavouritesList {
  id: string;
  name: string;
  items: Array<FavouriteItem>;
  shoppingListId?: string;
}

/** iCalendar sync information */
export interface ICalendarInfo {
  enabled: boolean;
  url?: string;
  token?: string;
}

/** A recipe ingredient */
export interface Ingredient {
  name: string;
  quantity?: string;
  note?: string;
}

/** Input for creating a new ingredient */
export interface IngredientInput {
  name: string;
  quantity?: string;
  note?: string;
}

/** A grocery list */
export interface List {
  id: string;
  name: string;
  items: Array<ListItem>;
}

/** A grocery list item */
export interface ListItem {
  id: string;
  name: string;
  checked: boolean;
  note: string;
  quantity?: string;
  category?: string;
}

/** A meal plan event */
export interface MealPlanEvent {
  id: string;
  date: string;
  title?: string;
  recipeId?: string;
  labelId?: string;
  details?: string;
}

/** A recipe */
export interface Recipe {
  id: string;
  name: string;
  ingredients: Array<Ingredient>;
  preparationSteps: Array<string>;
  note?: string;
  sourceName?: string;
  sourceUrl?: string;
  servings?: string;
  prepTime?: number;
  cookTime?: number;
  rating?: number;
  nutritionalInfo?: string;
  photoId?: string;
}

/** A collection of recipes */
export interface RecipeCollection {
  id: string;
  name: string;
  recipeIds: Array<string>;
}

/** Saved authentication tokens for resuming sessions */
export interface SavedTokens {
  userId: string;
  accessToken: string;
  refreshToken: string;
  isPremiumUser: boolean;
}

/** A store for organizing where to buy items */
export interface Store {
  id: string;
  name: string;
  sortIndex: number;
}

/** A filter for stores */
export interface StoreFilter {
  id: string;
  name: string;
  storeIds: Array<string>;
}
