/* auto-generated by NAPI-RS */
/* eslint-disable */
/** The main AnyList client for interacting with the API */
export declare class AnyListClient {
  /** Login to AnyList with email and password */
  static login(email: string, password: string): Promise<AnyListClient>;
  /** Create a client from saved tokens (for resuming sessions) */
  static fromTokens(tokens: SavedTokens): AnyListClient;
  /** Get the saved tokens for this session */
  getTokens(): SavedTokens;
  /** Get all lists */
  getLists(): Promise<Array<List>>;
  /** Create a new list */
  createList(name: string): Promise<List>;
  /** Get a specific list by ID */
  getListById(listId: string): Promise<List>;
  /** Get a list by name */
  getListByName(name: string): Promise<List>;
  /** Rename a list */
  renameList(listId: string, newName: string): Promise<void>;
  /** Add an item to a list */
  addItem(listId: string, name: string): Promise<ListItem>;
  /** Add an item with details to a list */
  addItemWithDetails(
    listId: string,
    name: string,
    quantity?: string | undefined | null,
    note?: string | undefined | null,
    category?: string | undefined | null,
  ): Promise<ListItem>;
  /** Delete an item from a list */
  deleteItem(listId: string, itemId: string): Promise<void>;
  /** Cross off (check) an item */
  crossOffItem(listId: string, itemId: string): Promise<void>;
  /** Uncheck an item */
  uncheckItem(listId: string, itemId: string): Promise<void>;
  /** Update an existing item */
  updateItem(
    listId: string,
    itemId: string,
    name: string,
    quantity?: string | undefined | null,
    note?: string | undefined | null,
    category?: string | undefined | null,
  ): Promise<void>;
  /** Delete multiple items at once */
  bulkDeleteItems(listId: string, itemIds: Array<string>): Promise<void>;
  /** Delete all crossed off (checked) items from a list */
  deleteAllCrossedOffItems(listId: string): Promise<void>;
  /** Get all recipes */
  getRecipes(): Promise<Array<Recipe>>;
  /** Get a specific recipe by ID */
  getRecipeById(recipeId: string): Promise<Recipe>;
  /** Get a recipe by name */
  getRecipeByName(name: string): Promise<Recipe>;
  /** Create a new recipe with full metadata support */
  createRecipe(options: CreateRecipeOptions): Promise<Recipe>;
  /** Add recipe ingredients to a list with optional scale factor */
  addRecipeToList(
    recipeId: string,
    listId: string,
    scaleFactor?: number | undefined | null,
  ): Promise<void>;
  /**
   * Update an existing recipe
   * Note: The recipe name cannot be changed (use the existing name in options)
   */
  updateRecipe(recipeId: string, options: CreateRecipeOptions): Promise<Recipe>;
  /** Delete a recipe */
  deleteRecipe(recipeId: string): Promise<void>;
  /** Delete a list */
  deleteList(listId: string): Promise<void>;
  /**
   * Upload a photo for use with recipes
   * Returns the photo ID which can be used with createRecipe
   */
  uploadPhoto(data: Buffer, filename: string): Promise<string>;
}

/** Options for creating a new recipe */
export interface CreateRecipeOptions {
  /** Recipe name (required) */
  name: string;
  /** List of ingredients */
  ingredients: Array<IngredientInput>;
  /** Preparation/cooking steps */
  preparationSteps: Array<string>;
  /** Recipe notes/description */
  note?: string;
  /** Source name (e.g., "Web", "Cookbook") */
  sourceName?: string;
  /** Source URL */
  sourceUrl?: string;
  /** Serving size (e.g., "4 servings") */
  servings?: string;
  /** Prep time in minutes */
  prepTime?: number;
  /** Cook time in minutes */
  cookTime?: number;
  /** Rating from 1-5 */
  rating?: number;
  /** Nutritional information */
  nutritionalInfo?: string;
  /** Photo ID (from upload_photo) */
  photoId?: string;
}

/** A recipe ingredient */
export interface Ingredient {
  name: string;
  quantity?: string;
  note?: string;
}

/** Input for creating a new ingredient */
export interface IngredientInput {
  name: string;
  quantity?: string;
  note?: string;
}

/** A grocery list */
export interface List {
  id: string;
  name: string;
  items: Array<ListItem>;
}

/** A grocery list item */
export interface ListItem {
  id: string;
  name: string;
  checked: boolean;
  note: string;
  quantity?: string;
  category?: string;
}

/** A recipe */
export interface Recipe {
  id: string;
  name: string;
  ingredients: Array<Ingredient>;
  preparationSteps: Array<string>;
  note?: string;
  sourceName?: string;
  sourceUrl?: string;
  servings?: string;
  prepTime?: number;
  cookTime?: number;
  rating?: number;
  nutritionalInfo?: string;
  photoId?: string;
}

/** Saved authentication tokens for resuming sessions */
export interface SavedTokens {
  userId: string;
  accessToken: string;
  refreshToken: string;
  isPremiumUser: boolean;
}
